.env.example
.gitignore
next.config.js
src/components/Layout/index.module.scss
src/components/Sidebar/index.module.scss
src/components/Sidebar/index.tsx
src/components/elements/StatusIndicator/index.module.scss
src/components/elements/StatusIndicator/index.tsx
src/components/elements/index.ts
src/contexts/Toast/index.tsx
src/contexts/apis/CoretimeApi/index.tsx
src/contexts/apis/RelayApi/index.tsx
src/contexts/apis/consts.ts
src/contexts/apis/index.ts
src/contexts/apis/types.ts
src/pages/_app.tsx
src/utils/muiTheme.ts

- Connect APIs
- API connection status in the sidebar

Connect API

---

src/components/Header/index.module.scss
src/components/Layout/index.tsx
src/components/elements/RegionCard/index.tsx
src/contexts/regions/index.tsx
src/models/types.ts

Part of #24
This PR:
- Renames 'Core ownership' to 'Coretime ownership'
- Makes 'consumed' work

Make region properties work

---

.env.example
next.config.js
src/contexts/apis/consts.ts
src/contexts/regions/index.tsx
src/contracts/xc_regions.json
src/models/types.ts
src/utils/functions.ts

Query xcRegions

---

src/components/Modals/Transfer/index.tsx
src/models/types.ts
src/pages/_app.tsx
src/utils/functions.ts

Xc-region transfers

---

src/components/Banner/index.tsx
src/components/Header/index.tsx
src/components/Layout/index.tsx
src/components/Modals/Interlace/index.tsx
src/components/Sidebar/index.tsx
src/components/elements/FeatureCard/index.tsx
src/components/elements/RegionCard/index.tsx
src/contexts/regions/index.tsx
src/pages/_app.tsx
src/pages/index.tsx

Makes CoreHub releasable to the public for testing to gather some initial feedback.

Cleanup & fixes

---

src/components/Modals/Sell/index.tsx
src/components/Modals/Unlist/index.tsx
src/components/elements/Label/index.tsx
src/components/elements/RegionCard/index.tsx
src/contexts/regions/index.tsx
src/contexts/sales/index.tsx
src/contracts/market.json
src/models/types.ts
src/pages/regions.tsx

Region unlisting

---

package.json
src/components/Modals/Partition/index.tsx
src/components/elements/ListingCard/index.tsx
src/components/elements/MarketFilters/DurationFilter.tsx
src/components/elements/MarketFilters/PriceFilter.tsx
src/components/elements/MarketFilters/RegionEndFilter.tsx
src/components/elements/MarketFilters/RegionStartFilter.tsx
src/components/elements/MarketFilters/coreOccupancyFilter.tsx
src/components/elements/MarketFilters/index.tsx
src/components/elements/MarketFilters/sort.tsx
src/components/elements/RegionCard/index.tsx
src/contexts/market/index.tsx
src/models/consts.ts
src/models/types/regionMetadata.ts
src/pages/market/marketplace.tsx
src/pages/regions.tsx
src/utils/functions.ts
src/utils/muiTheme.ts
styles/global.scss

Market filters

---

src/components/Modals/Transfer/index.tsx
src/components/Sidebar/index.tsx
src/contexts/regions/index.tsx
src/models/types.ts
src/pages/transfer.tsx
src/utils/crossChain/consts.tsx
src/utils/crossChain/transfer.tsx
src/utils/crossChain/utils.tsx
src/utils/functions.ts
src/utils/native/transfer.tsx

Xc transfer

---

src/components/Modals/Sell/index.tsx
src/components/elements/RecipientSelector/index.tsx
src/contexts/regions/index.tsx
src/contexts/regions/native/index.ts
src/contexts/regions/xc/index.ts
src/models/consts.ts
src/models/types.ts
src/pages/transfer.tsx
src/pages/transfer/ChainSelector.tsx
src/pages/transfer/RegionSelector.tsx
src/pages/transfer/index.tsx
src/utils/crossChain/consts.tsx
src/utils/crossChain/transfer.tsx
src/utils/crossChain/utils.tsx
src/utils/functions.ts
src/utils/native/approve.tsx
src/utils/native/init.tsx
src/utils/native/remove.tsx

Cross chain transfer functionality

Cross-chain transfers

---

package.json
src/components/Modals/Interlace/index.tsx
src/contexts/regions/native/index.ts
src/utils/native/init.tsx

Bump `coretime-utils` from `0.2.6` to `0.2.8`

---

src/components/Modals/WalletConnect/index.tsx

We should use `isInitialazied` instead of `isConnected`

Wallet connect fix

---

src/components/Elements/RegionCard/index.tsx
src/contexts/regions/index.tsx
src/contexts/tasks/index.tsx
src/pages/_app.tsx

Read tasks from workload as well.

Read workload

---

src/components/Elements/SaleInfoPanel/DetailCard/index.tsx
src/components/Elements/SaleInfoPanel/index.tsx
src/hooks/salePhase.tsx
src/hooks/salePrice.tsx
src/pages/purchase.tsx
src/utils/functions.ts
src/utils/sale/utils.test.ts
src/utils/sale/utils.ts

Sale info fixes

---

package.json
src/components/Modals/Interlace/index.tsx
src/contexts/regions/index.tsx
src/contexts/regions/native/index.ts
src/contexts/tasks/index.tsx
src/hooks/renewableParas.tsx
src/utils/functions.test.ts
src/utils/functions.ts

Companion for: https://github.com/RegionX-Labs/coretime-utils/pull/3

Bump coretime utils to 0.3.2

---

src/components/Elements/Cards/SalePhaseCard/index.tsx
src/components/Elements/Cards/index.ts
src/components/Panels/SaleInfoPanel/DetailCard/index.tsx
src/components/Panels/SaleInfoPanel/index.tsx
src/components/Panels/SalePhaseInfoPanel/index.tsx
src/components/Paras/ParachainTable/index.tsx
src/pages/index.tsx
src/pages/paras/index.tsx

- Removed the paraId link turning purple when clicked
- Renamed `parachain management` to `parachain dashboard`.
- Updated footer in parachain table
- Added tooltip for sale phase
- ...

Some fixes

---

src/components/Paras/ParaStateCard/index.tsx
src/components/Tables/ParachainTable/index.tsx
src/hooks/parasInfo.ts
src/models/enums.ts
src/pages/paras/renewal.tsx

Fix false renewals

---

src/contexts/market/index.tsx

We didn't correctly parse the onchain data.

Fix listings

---

src/contexts/sales/index.tsx

This is actually incorrect. The number of available cores increased: https://kusama.subsquare.io/referenda/410

Revert "Cores on sale fix"

---

.github/workflows/ci.yml
Dockerfile
LICENSE
README.md
package.json
src/consts/index.ts
src/contexts/account/index.tsx
src/pages/_app.tsx
src/pages/index.tsx

A more clear and descriptive name

Rename to coretime hub

---

src/components/Panels/SaleInfoPanel/index.tsx
src/components/Regions/Modals/Price/index.tsx
src/contexts/account/index.tsx
src/contexts/regions/index.tsx
src/contexts/sales/index.tsx
src/hooks/accountExtrinsics.ts
src/hooks/sale/purchaseHistory.ts
src/hooks/sale/saleDetails.ts
src/hooks/sale/salesHistory.ts
src/models/regions/sale.ts
src/pages/index.tsx
src/pages/transfer.tsx

The sale end timestamp was incorrect. This PR fixes that.
Also updates the labels to be more precise.

Fix sale related data

---

src/contexts/orders/index.tsx
src/models/common/consts.ts
src/utils/order.ts

Fix needed because of this change: https://github.com/RegionX-Labs/RegionX-Node/pull/195

Order total contributions fix

---

src/components/Transfer/contexts/transferState.tsx
src/components/Transfer/hooks/useTransferHandlers.ts
src/components/Transfer/transferActions.tsx
src/contexts/apis/CoretimeApi/index.tsx
src/contexts/apis/RegionXApi/index.tsx
src/contexts/apis/RelayApi/index.tsx
src/contexts/apis/common.ts
src/hooks/sale/purchaseHistory.ts
src/hooks/sale/saleDetails.ts
src/hooks/sale/salesHistory.ts
src/models/common/consts.ts
src/utils/sale/sales.test.ts

This PR adds some basic validation logic for transfers.
Additionally, with this PR, token decimals are no longer hardcoded, and some parts of the transfer code have been cleaned up.

Validate transfers

---

src/components/Paras/ParaDisplay/index.tsx
src/contexts/orders/index.tsx
src/hooks/order/processed.ts
src/pages/paras/renewal.tsx

This PR adds a warning if all the cores are sold out before attempting to make a renewal.

improve renewals

---

src/components/Regions/Modals/TaskAssign/index.tsx
src/components/Regions/RegionMetaCard/index.tsx

Currently we only show the task name, however it is useful to show the TaskId(ParaId) as well.

Show Task IDs

---

src/components/Transfer/transferActions.tsx
src/components/Transfer/transferForm.tsx
src/pages/paras/renewal.tsx

By looking at the code it should be self explanatory.

Flip origin and destination

---

.github/workflows/ci.yml
.gitignore
package-lock.json
src/hooks/renewableParas.ts

Hide expired renewals
